# Generated by Django 3.1 on 2021-03-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='recommend',
            field=models.BooleanField(default=True),
        ),
    ]
