# Generated by Django 3.1 on 2021-03-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210312_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='recommend',
            field=models.IntegerField(),
        ),
    ]
