# Generated by Django 3.1 on 2021-03-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='caution_money',
        ),
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.CharField(default='', max_length=50),
        ),
    ]
